[gn_scan_deployment_ip_collection]
field.noise = bool
field.RIOT = bool
field.internet_scanner_intelligence = bool
field.business_service_intelligence = bool
field.classification = string
field.trust_level = string
field.last_checked = string
field.code = string
enforceTypes = true

[greynoise_indicators_collection]
field._key = string
field.actor = string
field.first_seen = string
field.last_seen = string
field.classification = string
field.tags = string
field.cve = string
field.source_country = string
field.asn = string
enforceTypes = true

[gn_feed_collection]
field.query = string
field.created = string

[gn_overview_collection]
field.classification = string
field.stats_field = string
field.stats_value = string
field.stats_count = string
enforceTypes = true

[multi]
field._key = string
field.response = string
field.age = number
accelerated_fields.age_ascending = {"age":1}

[context]
field._key = string
field.response = string
field.age = number
accelerated_fields.age_ascending = {"age":1}

[riot]
field._key = string
field.response = string
field.age = number
accelerated_fields.age_ascending = {"age":1}
