[gnip]
filename = gnip.py
chunked = true
python.version = python3
python.required = 3.13

[gnquick]
filename = gnquick.py
chunked = true
python.version = python3
python.required = 3.13

[gnquery]
filename = gnquery.py
chunked = true
maxresultrows = 10000
python.version = python3
python.required = 3.13

[gnstats]
filename = gnstats.py
chunked = true
python.version = python3
python.required = 3.13

[gnmulti]
filename = gnmulti.py
chunked = true
python.version = python3
python.required = 3.13

[gncontext]
filename = gnip.py
chunked = true
python.version = python3
python.required = 3.13

[gnfilter]
filename = gnfilter.py
chunked = true
python.version = python3
python.required = 3.13

[gnenrich]
filename = gnenrich.py
chunked = true
python.version = python3
python.required = 3.13

[gnoverview]
filename = greynoise_overview.py
chunked = true
python.version = python3
python.required = 3.13

[gniptimeline]
filename = gniptimeline.py
chunked = true
python.version = python3
python.required = 3.13

[maintaincache]
filename = cache_maintenance.py
chunked = true
python.version = python3
python.required = 3.13

[gncve]
filename = gncve.py
chunked = true
python.version = python3
python.required = 3.13