[source::greynoise]
KV_MODE = json

[source::...greynoise_main.log]
sourcetype = greynoise_main

[greynoise_feed_indicators]
SHOULD_LINEMERGE = false
KV_MODE = JSON
TIME_PREFIX = \"last_seen_timestamp\"\s*:\s*\"
TIME_FORMAT = %Y-%m-%d %H:%M:%S
TRUNCATE = 999999

FIELDALIAS-bytes = internet_scanner_intelligence.raw_data.source.bytes AS bytes
FIELDALIAS-source = ip as src
FIELDALIAS-source_ip = ip as src_ip
FIELDALIAS-cves = internet_scanner_intelligence.tags{}.cves{} as cve
FIELDALIAS-tag_names = internet_scanner_intelligence.tags{}.name as signature
FIELDALIAS-intention = internet_scanner_intelligence.tags{}.intention as severity
FIELDALIAS-category = internet_scanner_intelligence.tags{}.category AS category
