[admin:app_greynoise_configuration]
match = /
members = app_greynoise_settings

[admin_external:app_greynoise_settings]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = app_greynoise_rh_settings.py
handleractions = edit, list
