[gn_scan_deployment_ip_lookup]
external_type = kvstore
collection = gn_scan_deployment_ip_collection
fields_list = _key, RIOT, noise, business_service_intelligence, internet_scanner_intelligence, classification, trust_level, last_checked

[gn_feed_lookup]
external_type = kvstore
collection = gn_feed_collection
fields_list = _key, query, created

[gn_overview_lookup]
external_type = kvstore
collection = gn_overview_collection
fields_list = classification, stats_field, stats_value, stats_count

[greynoise_indicators]
external_type = kvstore
collection = greynoise_indicators_collection
fields_list = _key, actor, first_seen, last_seen, classification, tags, cve, source_country, asn

[gn_multi_cache_lookup]
external_type = kvstore
collection = multi
fields_list = _key, response, age

[gn_context_cache_lookup]
external_type = kvstore
collection = context
fields_list = _key, response, age

[gn_riot_cache_lookup]
external_type = kvstore
collection = riot
fields_list = _key, response, age

[greynoise_ip_intel_malicious]
filename = greynoise_ip_intel_malicious.csv

[greynoise_ip_intel_suspicious]
filename = greynoise_ip_intel_suspicious.csv

[greynoise_ip_intel_unknown]
filename = greynoise_ip_intel_unknown.csv

[greynoise_ip_intel_benign]
filename = greynoise_ip_intel_benign.csv