---
repos:
  - repo: local
    hooks:
      - id: yamllint
        name: Style check (yamllint)
        entry: yamllint
        language: system
        exclude: ^bin/SA_GreyNoise/
        types:
          - yaml
      - id: black
        name: Style check (black)
        entry: black
        language: system
        exclude: ^bin/SA_GreyNoise/
        types:
          - python
      - id: isort
        name: Style check (isort)
        entry: isort
        language: system
        exclude: ^bin/SA_GreyNoise/
        types:
          - python
      - id: flake8
        name: Static analysis (flake8)
        entry: flake8
        language: system
        exclude: ^bin/SA_GreyNoise/
        types:
          - python
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
