[pytest]
testpaths = tests
pythonpath = .
            tests
            APP_FILES_ONLY/SA-GreyNoise/bin
            APP_FILES_ONLY/SA-GreyNoise/bin/SA_GreyNoise
addopts = -q
filterwarnings =
    ignore::DeprecationWarning
